name: QtStudentDBManagerCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Qt
      run: |
            sudo apt-get update
            sudo apt-get install -y build-essential git cmake gettext
            sudo apt-get install -y qtbase6-dev qtdeclarative5-dev qtquickcontrols2-5-dev libqt5remoteobjects5-dev libqt5serialport5-dev libkf5config-dev
            sudo apt-get install -y libkf5coreaddons-dev libkf5i18n-dev extra-cmake-modules

 #   - name: Install Qt
 #     uses: jurplel/install-qt-action@v2
 #     with:
 #       qt-version: '6.6.0'
 #       path
 #       what all things modules

    - name: Create Build Directory
      run: mkdir build

    - name: Run CMake and build
      run: |
            cmake -B build -S .
            make

    - name: Run Server
      run: ./build/server

    - name: Run Client
      run: ./build/client

    - name: Run Sync
      run: ./build/sync


