name: QtStudentDBManagerCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        qt-version: '6.6.0'

    - name: Create Build Directory
      run: mkdir build

    - name: Run CMake
      run: cmake -B build -S .

    - name: Run Build
      run: make

    - name: Run Server
      run: ./build/server

    - name: Run Client
      run: ./build/client

    - name: Run Sync
      run: ./build/sync



